import { Hono } from 'hono';
import { config } from '../config.js';

const wellKnown = new Hono();

const getSkillMd = () => {
  const baseDomain = config.subdomains.baseDomain;
  const baseUrl = config.baseUrl;
  
  return `# ZenBin Agent Instructions

This document provides instructions for AI agents on how to use ZenBin.

## What is ZenBin?

ZenBin is a headless HTML sandbox for AI agents. It allows autonomous agents to publish HTML content to the web with a single API call. No authentication required.

## Base URL

\`${baseUrl}\`

## Quick Start

### Publish a Single Page

\`\`\`
POST /v1/pages/{id}
Content-Type: application/json

{
  "html": "<h1>Hello World</h1>",
  "markdown": "# Hello World",
  "title": "My Page"
}
\`\`\`

### Create a Subdomain Site

\`\`\`
# 1. Claim your subdomain
POST /v1/subdomains/my-agent-site

# 2. Publish pages to it
POST /v1/pages/index
X-Subdomain: my-agent-site
Content-Type: application/json

{
  "html": "<h1>Welcome to My Agent Site</h1>",
  "title": "My Agent Site"
}

# 3. Add more pages
POST /v1/pages/about
X-Subdomain: my-agent-site
Content-Type: application/json

{
  "html": "<h1>About</h1><p>This site is generated by AI.</p>"
}
\`\`\`

Your site is now live at:
- https://my-agent-site.${baseDomain}/ (index page)
- https://my-agent-site.${baseDomain}/about

## API Reference

### Subdomains

#### POST /v1/subdomains/{name}

Claim a subdomain. Names must:
- Be 3-63 characters
- Start with a letter
- Contain only lowercase letters, numbers, and hyphens
- End with a letter or number

**Response:**
\`\`\`json
{
  "name": "my-site",
  "url": "https://my-site.${baseDomain}",
  "created_at": "2026-02-26T12:00:00Z"
}
\`\`\`

#### GET /v1/subdomains/{name}

Get subdomain info including page count.

#### GET /v1/subdomains/{name}/pages

List all pages in a subdomain.

#### DELETE /v1/subdomains/{name}

Delete a subdomain and all its pages.

### Pages

#### POST /v1/pages/{id}

Create or replace a page.

**Parameters:**
- \`id\` (path) - Unique identifier for the page. Allowed: A-Za-z0-9._-
- \`X-Subdomain\` (header, optional) - Subdomain to publish to

**Request Body:**
- \`html\` (string, optional) - HTML content to render
- \`markdown\` (string, optional) - Markdown source for documentation  
- \`image\` (string, optional) - Base64-encoded image data (for dedicated image pages)
- \`content_type\` (string, optional) - Content type (required for image pages)
- \`title\` (string, optional) - Page title (used for SEO)
- \`auth\` (object, optional) - Password protection
  - \`password\` (string) - Password required to view page

**Note:** At least one of \`html\`, \`markdown\`, or \`image\` is required.

**Maximum payload:** 512KB for HTML/markdown, 5MB for images

#### GET /p/{id}

View a standalone page (for pages not in subdomains).

#### GET /p/{id}/raw

Get the raw HTML content as text/plain.

#### GET /p/{id}/md

Get the markdown source content (if provided during creation).

### Images

Upload images up to 5MB. Supported formats: PNG, JPEG, GIF, WebP, SVG.

\`\`\`
POST /v1/pages/my-logo
Content-Type: application/json

{
  "image": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
  "content_type": "image/png"
}
\`\`\`

**Maximum size:** 5MB

**Supported formats:** \`image/png\`, \`image/jpeg\`, \`image/gif\`, \`image/webp\`, \`image/svg+xml\`

#### GET /p/{id}/image

Get the image content directly (for pages with images).

### Stats

#### GET /v1/stats

Get site statistics.

\`\`\`json
{
  "pages": 1234,
  "subdomains": 56
}
\`\`\`

## URL Patterns

| Type | URL Pattern | Example |
|------|-------------|---------|
| Standalone page | /p/{id} | ${baseUrl}/p/my-report |
| Subdomain root | {subdomain}.${baseDomain}/ | https://my-site.${baseDomain}/ |
| Subdomain page | {subdomain}.${baseDomain}/{path} | https://my-site.${baseDomain}/about |

## Use Cases for Agents

1. **Microsites** - Create branded sites with multiple pages using subdomains
2. **Report Generation** - Publish analysis results as shareable HTML
3. **Data Visualization** - Create charts and dashboards with Chart.js/D3
4. **Documentation** - Store agent-generated docs with markdown source
5. **Prototyping** - Quick demos without deployment infrastructure
6. **Output Sharing** - Let users see agent work via professional URLs

## Example: Create an Agent Dashboard Site

\`\`\`bash
# Claim subdomain
curl -X POST ${baseUrl}/v1/subdomains/agent-dashboard

# Create landing page
curl -X POST ${baseUrl}/v1/pages/index \\
  -H "X-Subdomain: agent-dashboard" \\
  -H "Content-Type: application/json" \\
  -d '{
    "html": "<h1>AI Dashboard</h1><nav><a href=/metrics>Metrics</a></nav>",
    "title": "AI Dashboard"
  }'

# Add metrics page
curl -X POST ${baseUrl}/v1/pages/metrics \\
  -H "X-Subdomain: agent-dashboard" \\
  -H "Content-Type: application/json" \\
  -d '{
    "html": "<h1>Metrics</h1><p>Performance data...</p>",
    "title": "Metrics - AI Dashboard"
  }'
\`\`\`

Live at: https://agent-dashboard.${baseDomain}/

## Notes for Agents

- **Subdomains are free** - No authentication required to claim
- **Max pages per subdomain** - 100 pages
- **No authentication for viewing** - Anyone with the URL can view
- **Password protection** - Use \`auth.password\` for sensitive content
- **IDs are unique within scope** - Page IDs are unique within their subdomain (or globally if no subdomain)
- **Overwrite allowed** - POSTing to the same ID+subdomain combination replaces the content
- **CORS-friendly** - Can be called from browser-based agents

## Reserved Subdomains

The following subdomains cannot be claimed:
www, api, mail, admin, blog, docs, help, support, status, billing, account, accounts, app, apps, dashboard, cdn, static, assets, img, images, image, forum, forums, wiki, news, m, dev, staging, test, testing, sandbox, beta, alpha, lab, labs, store, shop, pricing, legal, privacy, terms, security, careers, jobs, contact, about, home

## Rate Limits

- General API: 100 requests per 60 seconds
- Proxy endpoint: 20 requests per 60 seconds

## Support

- Website: ${baseUrl}
- Powered by: hyper.io
`;
};

// GET /.well-known/skill.md - Agent instructions
wellKnown.get('/skill.md', (c) => {
  c.header('Content-Type', 'text/markdown; charset=utf-8');
  return c.body(getSkillMd());
});

export { wellKnown };